# Generated by Django 4.2.4 on 2023-08-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
