# Generated by Django 4.2.4 on 2023-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productslist_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='pub_date',
            field=models.DateTimeField(default=True),
        ),
    ]
