# Generated by Django 4.2.4 on 2023-08-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productslist_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='pub_date',
            field=models.DateTimeField(verbose_name='...'),
        ),
    ]
