# Generated by Django 4.2.4 on 2023-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productslist_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
