# Generated by Django 4.2.4 on 2023-08-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productslist_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
