# Generated by Django 4.2.4 on 2023-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('qnty', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
