# Generated by Django 4.2.4 on 2023-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
