# Generated by Django 4.2.4 on 2023-08-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
