# Generated by Django 4.2.4 on 2023-08-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
