# Generated by Django 4.2.4 on 2023-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_gtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.CharField(default='Product Information refers to any information held by an organisation about the products it produces, buys, sells or distributes. In the context of Product Information management (PIM), this typically refers to information relating to the selling and/or marketing of products via digital channels', max_length=500),
        ),
    ]
