# Generated by Django 4.2.4 on 2023-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='maxScore',
            field=models.IntegerField(default=93),
        ),
        migrations.AlterField(
            model_name='exam',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
