# Generated by Django 4.2.4 on 2023-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_exam_maxscore_alter_exam_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
