# Generated by Django 4.2.4 on 2023-08-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_exam_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='student_id',
            new_name='examdet',
        ),
    ]
