# Generated by Django 4.2.4 on 2023-08-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_student_id_exam_examdet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
