# Generated by Django 4.2.4 on 2023-08-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_delete_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='ExamDate')),
                ('maxScore', models.IntegerField(default=93)),
                ('actualScore', models.IntegerField()),
                ('percentage', models.FloatField(blank=True, default=0, null=True)),
                ('examdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
